// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZPHBgGnlSu8mfzk4aG8P-ddYv_vl1Nxs',
    appId: '1:97476365758:web:851ff23c412391ded37def',
    messagingSenderId: '97476365758',
    projectId: 'memocho-b895b',
    authDomain: 'memocho-b895b.firebaseapp.com',
    storageBucket: 'memocho-b895b.firebasestorage.app',
    measurementId: 'G-X894VXPQE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIlh4t-8aAx6nFGtcjjkoMMdSfcq6TEqA',
    appId: '1:97476365758:android:33c6972d0ad41068d37def',
    messagingSenderId: '97476365758',
    projectId: 'memocho-b895b',
    storageBucket: 'memocho-b895b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRLXrn3j0YoQjfffZIV2n8A1W6ZFyfZQE',
    appId: '1:97476365758:ios:8cadb27345cec218d37def',
    messagingSenderId: '97476365758',
    projectId: 'memocho-b895b',
    storageBucket: 'memocho-b895b.firebasestorage.app',
    iosBundleId: 'com.example.memochou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRLXrn3j0YoQjfffZIV2n8A1W6ZFyfZQE',
    appId: '1:97476365758:ios:8cadb27345cec218d37def',
    messagingSenderId: '97476365758',
    projectId: 'memocho-b895b',
    storageBucket: 'memocho-b895b.firebasestorage.app',
    iosBundleId: 'com.example.memochou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZPHBgGnlSu8mfzk4aG8P-ddYv_vl1Nxs',
    appId: '1:97476365758:web:6a1d365e0adba663d37def',
    messagingSenderId: '97476365758',
    projectId: 'memocho-b895b',
    authDomain: 'memocho-b895b.firebaseapp.com',
    storageBucket: 'memocho-b895b.firebasestorage.app',
    measurementId: 'G-HXNS5D0Z6D',
  );

}